== Классы в Kotlin

link:https://kotlinlang.org/docs/classes.html[kotlinlang.org]

*_See:_* link:../../kotlin-basics/src/main/kotlin/common/cs013_classes/ClassesSample1.kt[ClassesSample1.kt]

=== 1. Введение

Классы в Котлине объявляются с использованием ключевого слова class. Объявление класса состоит из *_имени_* класса, *_заголовка_* класса (с указанием его параметров типа, основного конструктора и некоторых других вещей) и *_тела_* класса, окруженного фигурными скобками. И заголовок, и тело не являются обязательными; если у класса нет тела, фигурные скобки можно опустить.

[source, kotlin]
----
class Person { /*...*/ }

class Empty // пустой класс без тела
----

Класс в Kotlin имеет *_основной конструктор_* и, возможно, один или несколько *_вспомогательных конструкторов_*.

=== 2. Основной конструктор класса

Основной конструктор объявляется в заголовке класса и идет после имени класса и необязательных параметров типа:

[source, kotlin]
----
class C private constructor(a: Int) { /*...*/ }
// конструктор без аннотаций или модификаторов видимости?
// Ключевое слово 'constructor' можно опустить!
class Person(firstName: String) { /*...*/ }
----

Первичный конструктор инициализирует экземпляр класса и его свойства в заголовке класса. Однако заголовок класса не может содержать код, поэтому, если вам надо по-особенному инициализировать объект, вам нужно использовать *_блоки инициализации_* внутри тела класса. +
Блоки инициализации объявляются с помощью ключевого слова *_init_*, за которым следуют фигурные скобки. Они выполняются в том же порядке, в котором они появляются в теле класса, чередуясь с инициализаторами свойств:
[source, kotlin]
----
class InitOrderDemo(name: String) {
    var firstProperty = "First property: $name".also(::println)
    val secondProperty : String // val можно инициализировать в init-блоке
    init { // можно работать с уже засетанным полем name
        println("First initializer block that prints $name")
    }

    init {
        secondProperty = "${name.length}"
    }
}
----

Основной конструктор также может объявлять свойства mutable или immutable с помощью *_val_*\*_var_*. Также, как и с функциями, можно объявлять значения по умолчанию:

[source, kotlin]
----
class Person(
    val firstName: String,
    val lastName: String,
    var age: Int = 25, // trailing comma
) { /*...*/ }
----

=== 3. Вспомогательный конструктор класса

Вспомогательные конструкторы объявляется в теле класса, префикс *_'constructor'_* обязателен:

[source,kotlin]
----
class Pet(owner: Person) {
    init {owner.pets.add(this)
 }
}
----

Если у класса есть основной конструктор, он должен быть вызван в самом начале (через конструкцию 'this' до тела вспомогательного конструктора). Код во всех блоках инициализации и инициализации свойств выполняется до кода вспомогательного конструктора:

[source, kotlin]
----
class InitOrderDemo(name: String) {
    var firstProperty = "First property: $name".also(::println)
    val secondProperty
    init {
        secondProperty = "${name.length}"
    }


    constructor(name: String, property: String) : this(name) {
        firstProperty = property
       // secondProperty = property
       // Error, нельзя инициализировать val
    }
}
----