== Data classes в Kotlin

link:https://kotlinlang.org/docs/data-classes.html[kotlinlang.org], link:https://developer.alexanderklimov.ru/android/kotlin/data.php[alexanderklimov]

*_See:_* link:../../kotlin-basics/src/main/kotlin/common/cs021_data_classes/DataClassesSample.kt[DataClassesSample.kt]

=== 1. Введение

Если у класса указать ключевое слово data, то автоматически будут созданы и переопределены методы `toString()`, `equals()`, `hashCode()`, `copy()`. Скорее всего вы будете использовать этот вариант для создания полноценного класса-модели с геттерами и сеттерами. Подобные классы часто используются при работе с JSON:
[source, kotlin]
----
data class User(val name: String, val age: Int)
----

Классы данных *_не могут быть abstract, open, inner или sealed_*, так что класс данных *_не может использоваться в качестве суперкласса_*. +
Однако классы данных могут реализовать интерфейсы и наследоваться от других классов.

=== 2. ComponentN-функции. Деструктурирующее присваивание

При создании data-классов компилятор автоматически добавляет набор функций, с помощью которых можно обратиться к свойствам. Они известны как componentN-функции, где N - это номер свойства. Подсчёт номера идёт по порядку в объявлении класса:

[source, kotlin]
----
data class User(val name: String, val age: Int, val city: String)

val kirill = User("Kirill", 23, "Gomel")
// componentN() функции
println("component1(): ${kirill.component1()}, " +
        "component2(): ${kirill.component2()}, " +
        "component3(): ${kirill.component3()}")
----

ComponentN-функции позволяют использовать их в объявлениях деструктуризации. Деструктуризация позволяет разбить объект на несколько переменных:
[source, kotlin]
----
data class User(val name: String, val age: Int, val city: String)

val kirill = User("Kirill", 23, "Gomel")
// 2 переменных в одном месте
val (userName, userAge) = kirill
println(userName) // Kirill
println(userAge)  // 23

val (name2, _, city) = kirill
println(name2) // Kirill
println(city)  // Gomel
----

Можно пропустить через цикл.

[source, kotlin]
----
val users = listOf(User("Kirill", 23, "Gomel"), User("Alexander", 29, "Ratomka"))

for((username, _, usercity) in users){
        println("$username lives in $usercity")
}
----

=== 3. Свойства, объявленные в теле класса

Компилятор использует только свойства, определенные внутри основного конструктора, для автоматически создаваемых функций. Чтобы исключить свойство из сгенерированных реализаций, объявите его внутри тела класса:

[source, kotlin]
----
data class User(val name: String, val age: Int,
                val city: String) {
    var userId: UUID = UUID.randomUUID()
}
----

Тогда данная пропертя не будет, например, принимать участие в тех же функциях сравнения *_equals()_* и *_hashCode()_*.

=== 4. Копирование

Если вам потребуется создать копию объекта данных, изменяя некоторые из его свойств, но оставить другие свойства в исходном состоянии, воспользуйтесь функцией copy(). Для этого функция вызывается для того объекта, который нужно скопировать, и ей передаются имена всех изменяемых свойств с новыми значениями.

[source, kotlin]
----
val kirill = User("Kirill", 23, "Gomel")
val serafima = kirill.copy(name = "Serafima")

println("Copy obj: $serafima")
println("initial userId: ${kirill.userId}, " +
        "new userId: ${serafima.userId}")
----

Фактически мы создаём копию объекта, меняем значение нужного свойства и присваиваем новый объект переменной с новым именем. При этом исходный объект остаётся без изменений.